// effective.config.ts
// Generated by `npx effective init` on 2026-05-16.
// Review and edit; the comments explain each section.

import { defineConfig, seeds } from '@oftomorrow/effective';

export default defineConfig({
  // The recommended preset includes the full catalogue at strict severity.
  // See DESIGN.md for the constitution-as-substance reframe.
  extends: ['recommended'],

  // How to run your toolchain. Detected from package.json scripts and
  // devDependencies. Reporter flags are appended for the JSON parsers
  // `effective` ships; if a script already emits JSON, the flag is harmless.
  toolchain: {
    lint: 'pnpm lint --format json',
    typecheck: 'pnpm typecheck',
    test: 'pnpm test --reporter json',
    coverage: 'pnpm coverage --reporter json',
  },

  // Disable rules that don't fit your project. Rationale required.
  // Example:
  //   disable: {
  //     'spec.assertion-narrowed': 'We use property-based tests; false positives here.',
  //   },

  // Downgrade severity for rules you can't satisfy yet. Promote back as you catch up.
  // Example:
  //   override: {
  //     'exceptions.must-cite-justification': {
  //       severity: 'HIGH',
  //       rationale: 'Existing escape hatches lack refs; warn now, retrofit gradually.',
  //     },
  //   },

  // Define custom roles for workflows beyond test-writer / code-writer / reviewer.
  // Example:
  //   roles: {
  //     'migration-writer': {
  //       defaultEditable: ['migrations/**', 'test/migrations/**'],
  //       expectations: { newMigrationExists: true, existingTestsPass: true },
  //     },
  //   },

  // Exception registry — every escape-hatch comment in your code
  // (`c8 ignore`, `@ts-expect-error`, `eslint-disable`,
  // `prettier-ignore`) must cite an `exception-id:` matching one
  // of these. Built-in templates come from `seeds.builtInExceptions`;
  // add project-specific instances below the spread.
  exceptions: {
    ...seeds.builtInExceptions,

    // 'our-postgres-driver-quirk': {
    //   id: 'our-postgres-driver-quirk',
    //   category: 'external-library-drift-defense',
    //   mechanism: 'ts-expect-error',
    //   context: 'pg@8.x leaves stale connections under specific error shapes',
    //   retirementCondition: 'Resolved when we migrate to pg@9 or postgres.js',
    //   addedDate: '2026-05-16',
    //   status: 'active',
    // },
  },

  // Protected paths — constitutional files no worker should edit
  // without elevation. Init detected the entries below from your
  // project shape (lockfile, devDependencies, config files,
  // workflows). Distinct from the lane rule: lane authorizes which
  // files a scope can touch; `protected` asserts which files NO
  // scope touches without elevation.
  protected: [
    {
      path: 'effective.config.ts',
      rationale: 'The constitution itself. Workers must not edit the rules they are being held to.',
    },
    {
      path: 'eslint.config.*',
      rationale: 'ESLint config controls lint behavior; editing it changes what `verify` enforces.',
    },
    {
      path: '.eslintrc.*',
      rationale: 'ESLint config controls lint behavior; editing it changes what `verify` enforces.',
    },
    {
      path: '.eslintrc',
      rationale: 'ESLint config controls lint behavior; editing it changes what `verify` enforces.',
    },
    { path: 'tsconfig*.json', rationale: 'TypeScript config controls type-check strictness.' },
    { path: 'vitest.config.*', rationale: 'Vitest config controls what `tests-pass` means.' },
    {
      path: '.prettierrc*',
      rationale: 'Prettier config controls formatting; editing it shifts what passes format-check.',
    },
    {
      path: 'prettier.config.*',
      rationale: 'Prettier config controls formatting; editing it shifts what passes format-check.',
    },
    { path: '.husky/**', rationale: 'Pre-commit hooks enforce policy before code lands.' },
    {
      path: 'package.json',
      rationale:
        'Scripts and dependency declarations are constitutional; editing them changes what tools run. Workers legitimately needing new dependencies should surface that via kickBack rather than editing this file directly.',
    },
  ],

  meta: {
    name: '@oftomorrow/human-agent-chat',
    version: '1.0.0',
  },
});
